services:
  pdf-builder:
    build:
      context: .
      dockerfile: Dockerfile
    entrypoint: [node, src/build-pdf.js]
    volumes:
      - source: ./docs/resume.pdf
        target: /app/docs/resume.pdf
        type: bind
