services:
  pdf-builder:
    build:
      context: .
      dockerfile: Dockerfile
    entrypoint: [bun, src/build-pdf.js]
    volumes:
      - source: ./public/resume.pdf
        target: /app/public/resume.pdf
        type: bind
