services:
  html-builder:
    build:
      context: .
      dockerfile: Dockerfile
    entrypoint: [node, src/build-html.js]
    ipc: host
    volumes:
      - source: ./docs/index.html
        target: /app/docs/index.html
        type: bind
      - read_only: true
        source: ./resume.json
        target: /app/resume.json
        type: bind
  pdf-builder:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - html-builder
    entrypoint: [node, src/build-pdf.js]
    ipc: host
    volumes:
      - source: ./docs/resume.pdf
        target: /app/docs/resume.pdf
        type: bind
      - read_only: true
        source: ./docs/index.html
        target: /app/docs/index.html
        type: bind
      - read_only: true
        source: ./resume.json
        target: /app/resume.json
        type: bind
version: '3.7'
