version: "3.7"
services:
  pdf-builder:
    build:
      context: .
      dockerfile: Dockerfile
    ipc: host
    volumes:
      - type: bind
        source: ./docs
        target: /app/docs
    entrypoint: ["node", "buildPDF.js"]