name: deploy-github-page-after-push-master

on:
  push:
    branches:
      - master

env:
  CI: true
jobs:
  deploy:
    if: "!contains(github.event.head_commit.message, '[skip ci]')"
    runs-on: ubuntu-latest
    environment:
      name: master
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js LTS
        uses: actions/setup-node@v3.5.1
        with:
          node-version-file: '.nvmrc'
      - run: bash ./scripts/setup.sh
      - run: bash ./scripts/test.sh
      - run: bash ./scripts/build.sh
