env:
  CI: true
jobs:
  deploy:
    environment:
      name: master
    if: "!contains(github.event.head_commit.message, '[skip ci]')"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v2
      - run: bun install --frozen-lockfile
      - run: bunx playwright install chromium
      - run: |
          touch ./public/resume.pdf
          docker compose -f docker-compose-build.yml up --build --exit-code-from pdf-builder --abort-on-container-exit
      - run: bun scripts/build-html.js --prod
      - run: |
          cp public/resume.pdf dist/resume.pdf
          touch dist/.nojekyll
          cp public/resume.base.json dist/ || true
          cp public/CNAME dist/ || true
          cp public/.htaccess dist/ || true
      - name: Upload doc folder
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./dist
      - id: deployment
        name: Deploy doc with PDF to GitHub Pages
        uses: actions/deploy-pages@v4
name: deploy-github-page-after-push-master

on:
  push:
    branches:
      - master
permissions:
  contents: write
  id-token: write
  pages: write
