env:
  CI: true
jobs:
  deploy:
    environment:
      name: master
    if: "!contains(github.event.head_commit.message, '[skip ci]')"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js LTS
        uses: actions/setup-node@v4.0.3
        with:
          node-version-file: .nvmrc
      - run: bash ./scripts/setup.sh
      - run: bash ./scripts/test.sh
      - run: bash ./scripts/build.sh
      - name: Upload doc folder
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./docs
      - id: deployment
        name: Deploy storybook to GitHub Pages
        uses: actions/deploy-pages@v4
name: deploy-github-page-after-push-master

on:
  push:
    branches:
      - master
