name: deploy-github-page-after-push-master

on:
  push:
    branches:
      - master

env:
  CI: true
jobs:
  deploy:
    runs-on: ubuntu-latest
    environment:
      name: master
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 14.x
        uses: actions/setup-node@v2
        with:
          node-version: 14.x
      - run: bash ./scripts/setup.sh
      - run: bash ./scripts/test.sh
      - run: bash ./scripts/build.sh