env:
  CI: true
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{github.head_ref}}
      - name: Use Node.js LTS
        uses: actions/setup-node@v3.8.1
        with:
          node-version-file: .nvmrc
      - run: bash ./scripts/setup.sh
      - run: bash ./scripts/test.sh
name: Verify PR

on: pull_request
